### ISSUE TITLE
today the app doesn't seem to work properly

### ISSUE THREAD

**Issue by ARPAV2022** [isa-group/wecaremed#10]
**Describe the bug**
we cannot enter in the app. Both login and register buttons do not work.

**Desktop (please complete the following information):**
 - Browser chrome, firefox
 - Ve
![Screenshot from 2022-02-11 09-05-40](https://user-images.githubusercontent.com/98102967/153563594-6e720db1-076d-44c9-8c52-cc0b4386d633.png)
![Screenshot from 2022-02-11 09-04-57](https://user-images.githubusercontent.com/98102967/153563597-738979aa-45a6-463f-910b-6ddf60b479f6.png)
rsion [e.g. 22]

**Comment by MaToSan24** [comment]
Try to check again, the app should be working now

**Comment by ARPAV2022** [comment]
yes, thank you and also José Garcia for the fast support. Best regards
