### ISSUE TITLE
ARPAV equipment tab

### ISSUE THREAD

**Issue by ARPAV2022** [isa-group/wecaremed#12]
What is   intended for "computer central processes"?
Can we evaluate the   possibility to enter a bulk number equal to the sum of IT equipment (without   differentiate into categories)?
Is there a representative   emission factor for the entire IT equipment category (e.g. a mean value of   different IT categories CFs, if they are slightly different)?

**Comment by natlio** [comment]
- We suggest to remove "computer central processes" item since it has the same Emission Factor of "PCs"
- There is no a representative EF for all IT items since these are highly differentiated.
