### ISSUE TITLE
ARPAV events

### ISSUE THREAD

**Issue by ARPAV2022** [isa-group/wecaremed#14]
Does Label "Average number of physical participants" is the overall sum (local + non-local) or only local ones?
How we define "local" ?; may be more clear from the user's point of view to insert a distance threshold (in km) to separate local from non-local?
Or may we substitute "local" with the new label "not travalling from abroad" or similar?

**Comment by natlio** [comment]
- The Label "Average number of physical participants" is the overall sum (local + non-local). We have already proposed (see Issue 9) a restriction to be added so as the number of non-local participants not be greater than the "Average number of physical participants" 
- We propose a definition of the non-local physical participants to be added as an info in the tool as following; "Participants ravelling to the hosting city (national/international travel) only for the participation to the event"

**Comment by maxbre** [comment]
see issue 15
