### ISSUE TITLE
ARPAV general features

### ISSUE THREAD

**Issue by ARPAV2022** [isa-group/wecaremed#15]
Labels of the columns should be as clear as possible and provide to the user a clear link with the calculation algorithm behind the value: this simplifies and increases the awarness diuring the compilation 
the default value cannot be deleted automatically during the compilation; this could be a source of possible mistake when you fill the cell with a real number without deleting the default value
CF colors (red, yellow, green) should be based on robust considerations, sensitivity analysis and benchmarking > how to deal with it?
is it possible to create a copy of the same project to change only some variables and do sensitivity analysis?
Can the button SAVE be extended to the saving of the whole form instead of place it partially  in few tabs?

**Comment by natlio** [comment]
- Regarding the default values used in the tool we propose (if it is possible) that these cells to be e.g. grey so as to be easily identified by the user that it is a default value proposed by the tool. We agree that when the user clicks on the cell this value should be deleted automatically and the colour cell change to white as the rest ones.



AUTH

**Comment by maxbre** [comment]
title of the input fields should be as clear as possible for the user: e.g event tab, "average number of physical participant", please specify additional information in order to understand if we are talking about local or non local user
