### ISSUE TITLE
Uncorrect visualisation of CF values in the initial list

### ISSUE THREAD

**Issue by ARPAV2022** [isa-group/wecaremed#20]
In the initial list of projects,  the column of "CF estimation" is 0, even if the projects inside has values different from 0 (see screenshot)
![immagine](https://user-images.githubusercontent.com/98102967/165555245-bd472fd9-2e06-4341-8803-c66ee8fbcb43.png)

**Comment by MaToSan24** [comment]
As mentioned on issue #22, we have established initial and current data for each project (apart from simple and advanced modes), and this table shows only the CF values for the projects' current data. If you notice, the data that has been introduced in the first project has been put in the "Initial" side, not on the "Current", that is the reason why this table is not showing it.
