### ISSUE TITLE
list of new issues

### ISSUE THREAD

**Issue by maxbre** [isa-group/wecaremed#24]
section "partners"
------------------------------------------------------------------------------------------------------------------------------------------------
feature request:
- the list of countries is missing of Germany and Bulgaria: I understand that these two countries are not present in the list because they are not part of the MED area but they are needed for testing a project input data (PADOAVFIT), is it somehow possible to insert an "average" country of the MED area?
- please default in alphabetical order the names of countries from the dropdown menu "country"

to be check:
- default values to zero for all fields when a new partner is added, sometimes it seems not to retain (save) the input values

section "equipment"
------------------------------------------------------------------------------------------------------------------------------------------------
proposal:
"fax machines" is frankly an out of date equipment, it might be possibly eliminated with no harm at all

section "external events partecipated by the project"
------------------------------------------------------------------------------------------------------------------------------------------------
to be check against previous release of the tool:
it seems missing the input field "number of online events partecipated by the project" (as compared to the content of the export excel file for the collection of data)

save all button
------------------------------------------------------------------------------------------------------------------------------------------------
when clicked it says: ""The values of the project will be updated in it's initial phase, are you sure?"
what does it means the message? it means that all already entered data will be set to their default values?
please check consistency of the message text and its effect on entered data

------------------------------------------------------------------------------------------------------------------------------------------------
please check all these issues against the project
20220429 - test arpav PADOVAFIT

**Comment by MaToSan24** [comment]
> * the list of countries is missing of Germany and Bulgaria: I understand that these two countries are not present in the list because they are not part of the MED area but they are needed for testing a project input data (PADOAVFIT), is it somehow possible to insert an "average" country of the MED area?

![asd](https://user-images.githubusercontent.com/63660411/166438834-552f20ff-2f69-4f4d-a93a-3b06d88e8f12.png)
Bulgaria is part of the list of available countries and the country you can use as an "average" is "Europe", which uses the average values in Europe for everything.


> section "external events partecipated by the project"
to be check against previous release of the tool:
it seems missing the input field "number of online events partecipated by the project" (as compared to the content of the export excel file for the collection of data)

In the methodology, the events participated by the project are only "in presence":
![asd](https://user-images.githubusercontent.com/63660411/166439857-30a7a060-4c4d-4a2a-9528-f75b168d0357.png)



> save all button
when clicked it says: ""The values of the project will be updated in it's initial phase, are you sure?"
what does it means the message? it means that all already entered data will be set to their default values?
please check consistency of the message text and its effect on entered data

The message is fine since you are trying to "save all values" while being in the "initial data" view of the project:
![image](https://user-images.githubusercontent.com/63660411/166440048-e22ff221-963d-4677-bcda-d3ab588eb162.png)

If you wanted to modify the current values you should click on the toggle button in order to switch to the "current data" view:
![asd](https://user-images.githubusercontent.com/63660411/166440272-98a810cc-368e-468d-a660-ee57d0482152.png)

**Comment by MaToSan24** [comment]
> to be check:
> 
> * default values to zero for all fields when a new partner is added, sometimes it seems not to retain (save) the input values

Could you please tell us what steps have you followed in order for the input values not to be saved? I think that what could be going on is that you added a partner while being in the simple or in the advanced mode, then switched to the other mode, and then realized that there were missing values. This is correct because the partner data that you introduce in each mode is different, and so, there would be some empty fields if you switched modes.

**Comment by MaToSan24** [comment]
> ## section "equipment"
> proposal: "fax machines" is frankly an out of date equipment, it might be possibly eliminated with no harm at all

If AUTH agrees with the change, we will implement it right away.

**Comment by MaToSan24** [comment]
> * please default in alphabetical order the names of countries from the dropdown menu "country"

The list of countries has been sorted alphabetically.

**Comment by natlio** [comment]
> > ## section "equipment"
> > proposal: "fax machines" is frankly an out of date equipment, it might be possibly eliminated with no harm at all
> 
> If AUTH agrees with the change, we will implement it right away.

Yes, we agree.

**Comment by maxbre** [comment]
> > to be check:
> > 
> > * default values to zero for all fields when a new partner is added, sometimes it seems not to retain (save) the input values
> 
> Could you please tell us what steps have you followed in order for the input values not to be saved? I think that what could be going on is that you added a partner while being in the simple or in the advanced mode, then switched to the other mode, and then realized that there were missing values. This is correct because the partner data that you introduce in each mode is different, and so, there would be some empty fields if you switched modes.



> > to be check:
> > 
> > * default values to zero for all fields when a new partner is added, sometimes it seems not to retain (save) the input values
> 
> Could you please tell us what steps have you followed in order for the input values not to be saved? I think that what could be going on is that you added a partner while being in the simple or in the advanced mode, then switched to the other mode, and then realized that there were missing values. This is correct because the partner data that you introduce in each mode is different, and so, there would be some empty fields if you switched modes.


> > to be check:
> > 
> > * default values to zero for all fields when a new partner is added, sometimes it seems not to retain (save) the input values
> 
> Could you please tell us what steps have you followed in order for the input values not to be saved? I think that what could be going on is that you added a partner while being in the simple or in the advanced mode, then switched to the other mode, and then realized that there were missing values. This is correct because the partner data that you introduce in each mode is different, and so, there would be some empty fields if you switched modes.


it is very difficult to reproduce it, I just realise that sometimes it happens; it might be the case that you are mentioning; I'll pay more attention to that in the next data entry, ok consider that issue closed for now, thanks for the reply

**Comment by maxbre** [comment]
> > * the list of countries is missing of Germany and Bulgaria: I understand that these two countries are not present in the list because they are not part of the MED area but they are needed for testing a project input data (PADOAVFIT), is it somehow possible to insert an "average" country of the MED area?
> 
> ![asd](https://user-images.githubusercontent.com/63660411/166438834-552f20ff-2f69-4f4d-a93a-3b06d88e8f12.png) Bulgaria is part of the list of available countries and the country you can use as an "average" is "Europe", which uses the average values in Europe for everything.
> 
> > section "external events partecipated by the project"
> > to be check against previous release of the tool:
> > it seems missing the input field "number of online events partecipated by the project" (as compared to the content of the export excel file for the collection of data)
> 
> In the methodology, the events participated by the project are only "in presence": ![asd](https://user-images.githubusercontent.com/63660411/166439857-30a7a060-4c4d-4a2a-9528-f75b168d0357.png)
> 
> > save all button
> > when clicked it says: ""The values of the project will be updated in it's initial phase, are you sure?"
> > what does it means the message? it means that all already entered data will be set to their default values?
> > please check consistency of the message text and its effect on entered data
> 
> The message is fine since you are trying to "save all values" while being in the "initial data" view of the project: ![image](https://user-images.githubusercontent.com/63660411/166440048-e22ff221-963d-4677-bcda-d3ab588eb162.png)
> 
> If you wanted to modify the current values you should click on the toggle button in order to switch to the "current data" view: ![asd](https://user-images.githubusercontent.com/63660411/166440272-98a810cc-368e-468d-a660-ee57d0482152.png)

OK I'll use "Europe" to input an average data, by the way I was actually referring to Romania and not to Bulgaria (which is effectively present), never mind, as I said I'll use "Europe" instead, thanks for ordering alphabetically which makes much easier the selection of a country

**Comment by maxbre** [comment]
[Input Data List_FFS_PADOVAFIT.xlsx](https://github.com/isa-group/wecaremed/files/8610766/Input.Data.List_FFS_PADOVAFIT.xlsx)

for what is concerning the "external events partecipated by the project partners" and the "number of online events partecipated by the project", please refer to the attachment (see excel file) which is the template used for the collection of data for other projects (testing phase);

please check at row 71, highlighted in red

the compiled template in attachment was an export of the tables of the wecaremed online tool as you provided us for the collection of data from other partners;
it might be referring to an old version of the tool? 
or eventually, in case the field  "number of online events partecipated by the project" is not considered in the actual methodology, please update the export and provide use the new version
thank you
