### ISSUE TITLE
The REMEDIO project is uncompleted

### ISSUE THREAD

**Issue by ARPAV2022** [isa-group/wecaremed#25]
I notice that some partners from the REMEDIO project have been deleted after the update of the tool. I guess that this dramatically affect the result.
PLease, have you the possibility to check that all the data we inserted in the REMEDIO project have been  copy-pasted correctly in the new version of the tool?
Otherwise we have to chack again all the project.

Thank you

**Comment by MaToSan24** [comment]
What's missing in the REMEDIO project is the second page of the "Partners" table, we didn't realize there was second page and so it wasn't copied. Please, would you kindly add them again?

**Comment by ARPAV2022** [comment]
The REMEDIO project has been completed with the missing partners.

I renamed it as 20220506 test arpav - REMEDIO AND I LOST ALL THE VALUES ABOUT EVENTS. Please check the bug, because it could be annoying the loose of values if you rename the project. Now, I will fix it manually inseting again the values

**Comment by MaToSan24** [comment]
Could you please tell us what steps have you followed in order to clone the project and lose the values? I just cloned the "20220506 test arpav - REMEDIO" project and I have not lost any data.

**Comment by ARPAV2022** [comment]
I don't cloned the project actually.

I clicked on "Edit project"
I renamed the title
I clicked on "update"

The resulting project (without any value on "event") is avaialble in the tool with the title "20220506 test arpav - REMEDIO_for bug"

I hope it is enough clear, on the contrary please let me know

**Comment by ARPAV2022** [comment]
The bug and the solution are explained in #52
