### ISSUE TITLE
CF calculations for Transportation in Simple and Advanced Use

### ISSUE THREAD

**Issue by natlio** [isa-group/wecaremed#29]
In the simple use mode, I use the following input data 
<img width="1215" alt="image" src="https://user-images.githubusercontent.com/61784811/166481621-e2ac104f-e70a-4e50-8b73-568ea61a9250.png">

and I get 0.14tCO2e for transportation. 
<img width="1215" alt="image" src="https://user-images.githubusercontent.com/61784811/166481793-3e9ebaa3-522e-4d91-90fb-8d1e918a906c.png">

This value is not correct for Transportation with the new EF used, considering that I have inserted an 1 year project (i.e. 220 two-way travels for full time employee). 
Is it sure that the duration of the project is calculated properly in the simple use mode?  

On the other hand, in the advanced use of the tool the corresponding result seems correct (0.17tCO2e). 
<img width="1215" alt="image" src="https://user-images.githubusercontent.com/61784811/166485089-3dbf96c1-7adb-43a2-abad-aee9273bbe3c.png">
<img width="1215" alt="image" src="https://user-images.githubusercontent.com/61784811/166485168-f552df46-5dd2-4118-bd6e-f569533265dc.png">

**Comment by MaToSan24** [comment]
I have fixed the problem. The months are considered as we said previously. You can check that the "transportation" CF value is now correct in the "test" project that you created:
![image](https://user-images.githubusercontent.com/63660411/167394615-7678c0e3-fb49-490d-be38-f443593f767d.png)

**Comment by natlio** [comment]
Thank you, it seems fine now.
