### ISSUE TITLE
Implement Login and Register functionality

### ISSUE THREAD

**Issue by MaToSan24** [isa-group/wecaremed#3]

**Comment by natlio** [comment]
It seems that Registration is not always working. Today Safari and Google Chrome seem to work . However a different user tried with Mozilla but it didn't work. Also, previous days registration using chrome was not working so I am not sure if the problem is the browser.

**Comment by MaToSan24** [comment]
Could you please attach some info about the problem in order to reproduce the error like data introduced and error displayed by the app?

**Comment by natlio** [comment]
Finally, the registration works now properly. Thank you very much!
