### ISSUE TITLE
number of items listed per page

### ISSUE THREAD

**Issue by maxbre** [isa-group/wecaremed#31]
for a more effective management of the data entry and an easier review of the information I'm proposing the following new features:
- increase the number of project listed within a single page (10 projects per page)
- increase the number of partners listed within a single page (10 partners per page)

see attached file for reference
[new_feature.pdf](https://github.com/isa-group/wecaremed/files/8659571/new_feature.pdf)

**Comment by MaToSan24** [comment]
Thank you for the proposal, it has been implemented right away.

**Comment by maxbre** [comment]
thank you for the prompt implementation of the new feature

issue closed from my side

best
