### ISSUE TITLE
Events organised by the project 

### ISSUE THREAD

**Issue by natlio** [isa-group/wecaremed#32]
- Add an error when the field “Duration (hours/day) is higher than 24 in the advanced use mode (similar to simple use).

- Replace the name of the field "Duration (hours/day)" with "Duration (hours per day)" so as to be more clear (both in advanced and simple use modes).

**Comment by LuisUsrDev** [comment]
Implemented. You can already check it out.

**Comment by natlio** [comment]
In case of the duration of the events (in hours per day) when I insert e.g. 40 hours it does not give an error but inserts the maximum value (i.e.24). This is not very useful since the user may insert by mistake a wrong value (e.g. 40). Could you please implement an error check that will be shown to the user? In the past version of the simple use mode , an error text was shown to the user. The problem was that this error check was not implemented in the advanced use mode.

**Comment by LuisUsrDev** [comment]
Sorry for the error, it has been fixed.
