### ISSUE TITLE
Number of two-way travels - Advanced use

### ISSUE THREAD

**Issue by natlio** [isa-group/wecaremed#33]
1. In the section "Partners", replace the name of the field "Number two-way travels" with "Number of two-way travels”
2. In the section "Partners", add an * to the field “Number of two-way travels” with the following clarification: "The values of this field are referred only to staff members concerning the whole project duration".
3. In the section "External Experts", add an * to the field “Number of two-way travels” with the following clarification: "The values of this field are referred only to external experts concerning the whole project duration"

**Comment by LuisUsrDev** [comment]
Implemented. You can already check it out
