### ISSUE TITLE
Rename Fields/Add clarifications - Advanced Use

### ISSUE THREAD

**Issue by natlio** [isa-group/wecaremed#35]
We suggest the following minor modifications in the advanced use mode. Thank you. 

1. In the Partners section, add an * with “The values of this section refer to staff members (full time + part time) concerning the whole project duration”
2. In the Partners section, rename the field “Sum person months (full time+part time)” with “Person months”.
3. In the Partners section, remove the reference * in the field “Number of two-way travels” 
4. In the Partners section, rename the field “Number of two-way travels” with “Number of two-way travels for work commuting”
5. In the External Experts section, rename the field “Number of two-way travels” with “Number of two-way travels for work commuting”
6. In the events section , please add an * for the :Non-local participants similarly to the simple use : “Participants travelling to the hosting city (national/international travel) only for the participation to the event”
7. In the Project participation in events section, rename the field “Non-local physical participants” with “Number of project participants”
8. In the Project participation in events section, rename the title “Project participation in events” with “Project participation in in-presence events”
9. In the Project participation in events section, please remove the field “Type”
10. In the Printable deliverables section, please add a field with the label “Name” 
11. In the Printable deliverables section, in the tab “Deliverable Type” the list should be as following “Report type*, Article/Newsletter/Booklet, Brochure/Flyer, Poster/Rollup. So, you have to remove the brackets with the description of the default values. 
12. In the Printable deliverables section, rename the field “Average pages per copy” with “Number of pages per copy”
13. In the results section, rename the label “Equivalent carbon dioxide emitted ” with “CO2 equivalent emitted”  
14. In the results section, rename the label “CO2” with “CO2” (i.e. 2 should be subscript) 
15. In the results section, rename the “CF breakdown” with “Carbon Footprint breakdown”
16. In the results section, rename “Fuels Heat” with “Fuels (Heating)”

**Comment by MaToSan24** [comment]
The requested changes have been implemented, feel free to check them out.

**Comment by natlio** [comment]
Thank you very much. Could you please rename also the field "Virtual participants" in the events section to "On-line participants" so as to have the same term with the simple use mode?
Thanks again for your effort!

**Comment by natlio** [comment]
Also, is it possible to remove the field “Car Fuel Type” in the events participated by the project section and integrate it in the field “Travel mode”  by adding the different travel modes for cars e.g. Car - Diesel, Car - Petrol etc?

**Comment by natlio** [comment]
Number 14 was not implemented. However , I see that I didn't write it with a subscript finally. I cannot copy it here. I mean like this 
<img width="59" alt="image" src="https://user-images.githubusercontent.com/61784811/169385716-c0ae9344-4260-4ec3-b3f1-6b1f2e6c797e.png">
Is this possible?

**Comment by LuisUsrDev** [comment]
The requested changes of the simple mode have been implemented, feel free
to check them out.

**Comment by MaToSan24** [comment]
Sorry for the inconvinience, the "CO2"s have been correctly updated to "CO₂"s and the virtual events have been renamed to on-line eventes.

> Also, is it possible to remove the field “Car Fuel Type” in the events participated by the project section and integrate it in the field “Travel mode” by adding the different travel modes for cars e.g. Car - Diesel, Car - Petrol etc?

Regarding this feature, it would be quite cumbersome, but it could be done. Do you have any problem with the current implementation?

**Comment by natlio** [comment]
> Sorry for the inconvinience, the "CO2"s have been correctly updated to "CO₂"s and the virtual events have been renamed to on-line eventes.
> 
> > Also, is it possible to remove the field “Car Fuel Type” in the events participated by the project section and integrate it in the field “Travel mode” by adding the different travel modes for cars e.g. Car - Diesel, Car - Petrol etc?
> 
> Regarding this feature, it would be quite cumbersome, but it could be done. Do you have any problem with the current implementation?

Thank you very much for the changes. 
It is ok.It is not so necessary to do it if this is difficult. We do not have any problem with the current implementation. We just thought that in that way it would be more easy to the user. Thanks again!
