### ISSUE TITLE
Criticalities to upload the project 20220506 test arpav - REMEDIO

### ISSUE THREAD

**Issue by ARPAV2022** [isa-group/wecaremed#36]
The app starts a strange intermitting recharge in contiuous if one switches from initial to current in the advance use mode.
Then you are not able to operate in the app and change the values.

**Comment by MaToSan24** [comment]
We are currently trying to figure out why this happens all of a sudden even if previously it was working fine. Even though, I've fixed it manually in this particular case in order to allow you to keep testing the tool without problems.

**Comment by MaToSan24** [comment]
We think that we have solved the problem. We are going to upload it. If you face this problem again don't hesitate in telling us.
