### ISSUE TITLE
Advance tool: decimal digits are not allowed in External experts "Person months"

### ISSUE THREAD

**Issue by ARPAV2022** [isa-group/wecaremed#39]
It seems that no decimal digits are allowed in the advance tool for External experts "Person months" , while (at least in REMEDIO) we digit 0.5 in the simple use.
![immagine](https://user-images.githubusercontent.com/98102967/170702514-74087f4a-c432-47ff-aa8b-e6917ed64c58.png)

**Comment by MaToSan24** [comment]
You need to input the decimal values with a comma, although in the resulting table they will be shown with a dot.

![image](https://user-images.githubusercontent.com/63660411/170735003-2eac8672-97e8-4e72-925d-2f25969d55e5.png)
![image](https://user-images.githubusercontent.com/63660411/170735068-f900cb07-1d46-4899-ba83-070db499c901.png)

**Comment by ARPAV2022** [comment]
![immagine](https://user-images.githubusercontent.com/98102967/170934372-bd9e44ee-f395-4f32-b79f-eae17086f248.png)

Your suggestion is fine for "partners" tab, while in the "External"'s person months I cannot add any decimal digits

**Comment by MaToSan24** [comment]
Sorry, you are right. It has been fixed and updated in the tool.

**Comment by ARPAV2022** [comment]
ok thank you Issue solved
