### ISSUE TITLE
AUTH - changes needed in the updated version of simple use 

### ISSUE THREAD

**Issue by natlio** [isa-group/wecaremed#4]
**Events:** 
a.The comment shown as "* The values of this section are considered the same for each project partner” would be better to replaced with "The values of this section are referred to the whole project partnership” 
b. In the tab “On-line” Events, you have to correct the name of the input "Average duration (days)” with "Average duration (hours)".

**Printable Deliverables**
a. You can remove the tab "Deliverable Name" since it is not needed for the calculations. The user should define only the type of deliverable (among with the 4 basic categories) and the number of copies.
b. You can just add a comment somewhere about the detailed list of deliverable types of the category Report Type e.g. "* Report/Plan/Analysis/Study/ Methodology/Manual/Guidance/ Roadmap/Strategy/Proceedings"

**Comment by MaToSan24** [comment]
The suggested replacements have been made and the second column of the printable deliverables table has been removed. Also, an asterisk below the mentioned table has been introduced listing the deliverables that are included in the "Report type" category.

These changes are already deployed so feel free to keep testing the tool.
