### ISSUE TITLE
Advance tool: numbers are not stable

### ISSUE THREAD

**Issue by ARPAV2022** [isa-group/wecaremed#40]
![immagine](https://user-images.githubusercontent.com/98102967/170705654-9f6a5a85-2c55-49bc-b171-983eb17ec321.png)

Switching from simple to advance it happens that numbers are lost. In the picture, all the row of the columns were filled in.

**Comment by MaToSan24** [comment]
I have explained the reason for this on issue #38 , please make sure to check it out. Please, do not forget to click on the "save" button before switching views.

**Comment by ARPAV2022** [comment]
OK I will put more attention, It would be useful to "authorise" to switch only if the project is saved or as alternative solutions exit with a pop up as remind to save the project

**Comment by MaToSan24** [comment]
We have added another mechanism in order to ensure that the data is not lost whenever editing it. Now, you should not lose the data that you input anymore.
