### ISSUE TITLE
Advance mode: participation in in presence events

### ISSUE THREAD

**Issue by ARPAV2022** [isa-group/wecaremed#43]
![immagine](https://user-images.githubusercontent.com/98102967/171418958-28e76e90-5b8c-4fec-80a9-98ecd1f6f34b.png)

I propose to add the possibility to insert decimal digits in duration (days) column (e.g. 1.5) >> red line

Do you think it is necessary to double the information for the daparture /arrival columns? Or in the case of commuting we can ask to the user to insert the km, type of trasnport and fuel just once time, considering a two-way trip?

**Comment by natlio** [comment]
The travel mode used may be different while arriving at or departing from the hosting city. So, we think it is important to keep the whole information.

**Comment by MaToSan24** [comment]
The possibility to insert decimal digits in the duration (days) column has been implemented.

**Comment by ARPAV2022** [comment]
Thank you for your comments. I can close the issue
