### ISSUE TITLE
Events in the advance mode - methodological issue

### ISSUE THREAD

**Issue by ARPAV2022** [isa-group/wecaremed#46]
Compliting REMEDIO events (participated in events by project staff) in more than one situation, it happens that the project staff come from different part of Europe (for example n.2 from Italy and n. 1 from Greece for a total of 3 participants). In the guidelines for the applicants we suggest to insert an average (or the highest) value of the distances in order to insert 1 row for each event, or as alternative split the same event in different rows according to the different origins of project participants?

here an example. In this case I account the higher distance among Italy-Spain and Greece-Spain for all the three participants
![immagine](https://user-images.githubusercontent.com/98102967/173088835-5c5dc337-8880-4f0c-b874-430d96407f97.png)

**Comment by natlio** [comment]
We suggest the second option: split the same event in different rows according to the different origins of project participants.

**Comment by ARPAV2022** [comment]
Thank you for your feedback; please, USE (or AUTH), remind to insert this hint in the user manual of the tool
