### ISSUE TITLE
Scenario data from Base mode data

### ISSUE THREAD

**Issue by ARPAV2022** [isa-group/wecaremed#47]
As far as I understood, the data from the Base mode should be copied directly when the user switch to Scenario mode, but this is not the case when I play in the REMEDIO project.
Thank you Giacomo

**Comment by MaToSan24** [comment]
This feature has been implemented in such way that the user is provided a button that allows him to export the data from the base mode to the Scenario/Monitoring Period mode, overwriting the data that Scenario/Monitoring Period modes contained.

You can already use this feature as the tool has been updated with it.

**Comment by ARPAV2022** [comment]
Ok, it works, but as far as I understood in the CF design mode the "base" and "scenario" switch is not more useful becausee the inter-scenario comparison will be do supported by the "My projects" list.
