### ISSUE TITLE
Printable materials: insert or not T-shirt

### ISSUE THREAD

**Issue by ARPAV2022** [isa-group/wecaremed#48]
This is a methodological issue to share with AUTH  @NAtlio.
Detailing the printable materials of REMEDIO project, among other communication materials, also project T-shirts have been produced (n.60). Comparing the unitary CF parameters of a paper printable deliverable and a T-shirt do we foresee relevant the integration of T-shirt to account among printable deliverables? We have to consider also the technical effort to do this minor modification. If the effort is high, we can insert it as missing item (and possible improvement) of the tool in the methodological manual. Thank you

**Comment by natlio** [comment]
In case of T-shirts, we could  estimate the CF of the material use of a T-shirt in some way. For example, the EF of clothing is 22310 kgCO2/tonne. If we consider that a T-shirt weights approximately e.g. 130gr then for 60 T-shirts we would have a total CF of 0.17tonnes CO2e.
However, if we add T-shirts in the materials section then we have to add additional items such as USB-sticks , bags, canteens etc. that are usually given to the participants of public events. At the moment, we think that it is very difficult to calculate the carbon footprint of all these materials which they may have different weight or consist of different materials etc while we have not found any statistical data for these items. 
So, we suggest not to include CF calculations for T-shirts in the tool.

**Comment by ARPAV2022** [comment]
I agree, thank you for the explanation. Maybe we could insert those items as further development /improvement of our tool. I close the issue. Thank you all
