### ISSUE TITLE
CF design mode - "Events" data are not cloned in Base mode

### ISSUE THREAD

**Issue by ARPAV2022** [isa-group/wecaremed#49]
I created a new project "Incircle_original" with realted data (also Events where present).
I cloned the project and all the data fo the different categories have been copied, but no the data related to the Events.

I worked in the Design mode, with base option (not scenario).
Thank you

**Comment by MaToSan24** [comment]
We have checked it and the "Incircle_original" has no Events data, and so, if you clone it, the Events data of the clone is empty. We have modified the Events data of the original project, then cloned it and the resulting clone had the corresponding modifications. We have left the project as it was originally before we checked it so you can see it yourself.

**Comment by ARPAV2022** [comment]
Ok, I think that the losting cause is when you update the characteristics of the project (see #52 )
