### ISSUE TITLE
Additional Data - Scenarios

### ISSUE THREAD

**Issue by natlio** [isa-group/wecaremed#51]
Regarding the setting of scenarios in the tab "Additional Data" the following changes should be made both in Design and Monitoring modes according to the decisions had been made regarding the implementation of scenarios.

1. In the tab "Transportation" the table Percentage distribution (%) of cars fleet by technology (fuel) for EU should be removed.
3. In the tab "Events" two subtabs should be added; a) Moving from/to the Hosting Place, b) Materials. In the subtab "Moving from/to the Hosting Place" only the table Percentage distribution of travels by main travel mode (%) should exist. In the subtab "Materials" the table "Percentage distribution of materials use" should exist.

Thank you in advance.

**Comment by natlio** [comment]
Just to clarify that in the tab "Events" the table "Percentage distribution of international and national travels for events" should be removed as it has been decided and replaced with the following table : "Percentage distribution of travels by main travel mode (%) ". This table is used for the calculation of CF for the Moving from/to the Hosting Place, so it could be renamed also as  "Percentage distribution of travels by main travel mode (%) for Moving from/to the Hosting Place".
Also, the table in the tab "Materials" should exist ALSO in the tab Events, so as the user could set different percentages for the material use in case of the material use by employees and events, respectively. 
Thank you again.

**Comment by MaToSan24** [comment]
> Also, the table in the tab "Materials" should exist ALSO in the tab Events, so as the user could set different percentages for the material use in case of the material use by employees and events, respectively.

This is not possible because the table used in the methodology, excels provided and in the application for the calculation of CF regarding primary, recycled and reused material usage is the same for employees and events, they are not independent tables.

**Comment by MaToSan24** [comment]
The same applies to trasportation for events, the same table is used as for transportation for commuting.

**Comment by natlio** [comment]
In the design mode, in case of work commuting (i.e. employees) the percentages of the country of each partner are used in the calculations while for events the percentages for Europe are used. 
In the monitoring mode,  in case of work commuting (i.e. employees) the percentages of the country of each partner or external experts are used in the calculations while for events the percentages of each hosting country are used. 

This is something that it has already been tested. Based on this, in the current version of the tool the following changes should be made in "Additional data" tab regarding work commuting and events. (I noticed that yesterday the name of this tab had changed to “variables of scenarios” but today it is different again as previously) 

A. In the design mode,
 1.  “Transportation for commuting” : the percentages should be given per country similarly to the monitoring mode. 
2. Materials : Is it possible this table to be different for each country ? (in order the user has the possibility to change these percentages for each partner)
3. Events: The table  "Percentage distribution of international and national travels for events" should be removed. The table "Percentage distribution of travels by main travel mode (%) for Moving from/to the Hosting Place“ should be added showing only the percentages for Europe. Also, it is important to add the table for materials in case of events since different policy would be followed by employees and events. Please check it again and let me know if this is finally possible. 

B. In the monitoring mode,
1. Materials : Is it possible this table to be different for each country ? (in order the user has the possibility to change these percentages for each partner or external expert)
2. Events: The table  "Percentage distribution of international and national travels for events" should be removed. The table "Percentage distribution of travels by main travel mode (%) for Moving from/to the Hosting Place“ should be added per hosting country. However, Is it possible this table to be per event (organized by the project)? Also, the table for materials should be added in the tab events. 

Please check the above comments and let me know if the suggested changes are feasible. Thank you very much for your effort.

**Comment by jabv2022** [comment]
Dear Natalia, these changes that you are proposing affect significantly to the tool database structure. It also requires the modifications of a lot of code, and several screens. In fact, there is a change in the methodology reflected in the excell files that was used for developing the tool.
Considering the close meeting with the JS,  summer breaks, and that validation and deployment of the tool is still pending, i think that its going to be very difficult to implement these modifications in time. In any case, we kindly ask you to updated and send us the excells files that you developed, and that was followed for the developing of the tool, in order to reevaluate the feasibility of the modifications.

**Comment by natlio** [comment]
Thank you for the response. I understand that the time is very limited and of course any possible change should not require such time. Indeed, in case of materials the same default values of percentages were used for all partners as well as for the case of employees and events, so, I understand that this requires the addition of extra tables in the tool which is difficult in the current stage. However, I will update the excel files as you suggest and I will send them back to check it again.
However, I cannot understand well the case of transportation. 
In the design mode, in the current version of the tool, in the additional data for transportation for commuting the table Percentage distribution of travels by main travel mode (%) (Europe) is shown. This is not correct, since in the methodology as well as in the excel files these percentages are different for each country (i.e. partner). So, in the design mode, this table should be per country (similar to monitoring mode) excluding the values for "Europe". Thus, in the events tab, the corresponding values for Europe would be only shown. These calculations are implemented in the excel files.   A similar case is for monitoring mode, where in the excel files the percentages used were different for each hosting country (in case of events) and each country of partners/external (in case of work commuting). Could you please confirm this? Or do you mean that the problem is that the values used for each case are taken from the same table (even if different values are used  in case of employees and  events depending on the country selected)? 
We could make also a short meeting for further clarification. Thank you.

**Comment by MaToSan24** [comment]
I think this issue has been finally solved with the latest updates of the tool. Could you confirm it please?

**Comment by natlio** [comment]
Yes , I confirm. I will close the issue.
