### ISSUE TITLE
Decimal value for part time and full person staff

### ISSUE THREAD

**Issue by ARPAV2022** [isa-group/wecaremed#53]
Do you think it is possible to allor the user to insert decimal digits in the values of the "number of part time /full time employees"?
If it is not the case, I woudl kindly ask you to specify this info in the guidelines.

**Comment by MaToSan24** [comment]
It is possible, but does it make sense? Keep in mind that the fields "number of part time / full time employees" are later multiplied by the "Sum of the staff person months (full time + part time)", which can be decimal if that is what you need.

**Comment by ARPAV2022** [comment]
I think that it makes sense because the values are methodological connected with different aspects (communiting VS office activity) and if there are not technical constraints I would open to users this possibility. This need arose during the collection phase of data from different projects. Thank you

**Comment by MaToSan24** [comment]
You can now input decimal values in the demanded fields.

**Comment by ARPAV2022** [comment]
OK thank you very much
