### ISSUE TITLE
Support to the user in the scenario analysis

### ISSUE THREAD

**Issue by ARPAV2022** [isa-group/wecaremed#54]
I worked a bit with the "Additional data" tab: 
1) is it possible to present the data in % terms instead of decimal digit?
2) If not, please consider to round the values at the second decimal digits in order to simplify the calculation of the user.
3) I suggest to add "Transportation for commuting" for the first sub-label of senario analysis
4) I would suggest to rename "Additional data" as "Variables of scenario analysis"
5) I don't rember what we agreed, but in my opinion the "Percentage distribution (%) of cars fleet by technology (fuel) for EU" is not something that the user can easly gather from his/her/it experience or from partyners' one.

**Comment by MaToSan24** [comment]
3, 4 and 5 have been implemented. Regarding 1 and 2, the numbers shown are the same as provided in the Excel, it is not possible to show them as percentages and allow editing at the same time, as well as if we show them rounded, they would be rounded in the database as well and would not follow the values provided in the methodology.

**Comment by jabv2022** [comment]
Dear all: 

I have notice some contradictions between what we agree and what Arpav is proposing here.

3. The different scenarios proposed by Auth (for example "Transportation for comuting") are going to be implemented manually by the user cloning the project and following the instructions included in the guide of the tool to implement the scenarios. So,  sub-labels of scenario analysis should not be included.
4. In the same way, the label should not be name as "Variables of scenario analysis". I recommend to get back to "Additional data"

**Comment by ARPAV2022** [comment]
Ok with the label "Additional data", but it is importnat to have clear and transparent guidelines for the user.
