### ISSUE TITLE
"CF estimation" values shown in "My project" list

### ISSUE THREAD

**Issue by ARPAV2022** [isa-group/wecaremed#55]
In the CF estimation column some values does not appear even if a value has been calculated 

![immagine](https://user-images.githubusercontent.com/98102967/176369871-ce4e46d4-18d6-4d15-b055-483417b3bc0a.png)

![immagine](https://user-images.githubusercontent.com/98102967/176370102-3f1111d9-56eb-4eee-999c-d1d39b93dfdc.png)

**Comment by MaToSan24** [comment]
This bug has been fixed, sorry for the inconvenience.

**Comment by ARPAV2022** [comment]
Ok thank you very much
