### ISSUE TITLE
CF etimation in My list not updated with scenario analysis

### ISSUE THREAD

**Issue by ARPAV2022** [isa-group/wecaremed#56]
I cloned the UTC project in orther to do a sensitivity analysis
I trasnform the material percentage from 100% of primary to 100% recycled for all the material
I recalcuted the CF and 101...appears (also in the value on the top of the page, while the value in "My project" list is still the previous one (131...)
![immagine](https://user-images.githubusercontent.com/98102967/176386344-f4776da5-f316-4cef-bec0-be48e95e8172.png)

![immagine](https://user-images.githubusercontent.com/98102967/176386436-be643ba4-bd66-4ffc-bde3-846f2a94156f.png)

**Comment by MaToSan24** [comment]
This bug has been fixed, sorry for the inconvenience.

**Comment by ARPAV2022** [comment]
OK thank you very much
