### ISSUE TITLE
Comments on Analysis feature

### ISSUE THREAD

**Issue by ARPAV2022** [isa-group/wecaremed#57]
![Uploading immagine.png…]()

I exported the data from an hypothetical CF best scenario to the Monitoring mode.
I updated value of the monitoring mode, supporing the report of the year 1 of implementation.
I went to Analysis tab and I compare the graph; some comments arose:
1) Different scale of the two figures do not allow an easy comparison 
2) The merging of the data in one figure could provide an easier understanding of the reporting status
3) If the point 2 is possible, I would fix the values of the "Project base data" (in other terms the "CF best scenario") in the axis and in the figure the "project reporting period data" are shown as percentage to those values

I hope that the explanation is enough clear, otherwise we can fix a fast meeting in order to clarify these aspects.
Thank you

**Comment by MaToSan24** [comment]
Could you check the current implementation of the analysis feature and give us your feedback about its current state again? Thank you in advance.

**Comment by ARPAV2022** [comment]
Thank you for the updates.

![immagine](https://user-images.githubusercontent.com/98102967/177490313-ded50d5c-b165-4f83-87c5-8329aea32f43.png)

I compared the UTC project year3 with the CF design phase with the analysis feature, but the Kiviat diagram seems not to correspond to the mathematical calculations:

I divided the electricity value of monitoring phase (41.11) by the CF design phase one (55.64) and I expected to have around 0.76, but in the diagram the point is fixed slightly more than 0.3. The same considerations can be done for all the other categories and the calculated percentages do not correspond with the represented Kiviat values.

In other word I would expect that Kiviat diagram is able to show to the user the amount of CF monitored and emitted compared to the estimated budget during the CF design phase for each category.

Values CF Design mode
![immagine](https://user-images.githubusercontent.com/98102967/177488299-5811c886-52ff-43b6-83d6-72139a038c0a.png)

Values CF monitoring 3 year
![immagine](https://user-images.githubusercontent.com/98102967/177488471-d9c2d3e5-939e-43ca-a748-dd65681da7a2.png)

Please note that the result of the ration monitoring/design values can be hiogher than 1 (see for example Materials in UTC project for which the ratio is equal to 5.24). In this case, fixing as 100% the "CF design mode"  I would expect that the pink line of the Kiviat diagram proportionally exeeds the e value 1 for that specific category.

I hope the comments are clear, othewise feel free to ask to arrange a fast meeting. Thank you again

**Comment by MaToSan24** [comment]
The analysis view has been updated, feel free to check it out again and tell us if there is still something wrong. Thank you.

**Comment by ARPAV2022** [comment]
Thank you, in my opinion the proposed version is more significant for the monitoring effort. I would ask if it is possible to highlight the line corresponding to the value 1 (e.i. 100% of the CF best option) that is a sort of threshold for the applicant.
Thank you in advance.

**Comment by MaToSan24** [comment]
A black highlighting has been added for the 100% of the best option.
![image](https://user-images.githubusercontent.com/63660411/178253097-772173a5-55bf-4998-a9ca-dcb5d318a2a5.png)
![image](https://user-images.githubusercontent.com/63660411/178253502-aef48905-e429-4099-9bc9-18de7ec995b2.png)
