### ISSUE TITLE
Exporting of scenario values in the monitoring phase

### ISSUE THREAD

**Issue by ARPAV2022** [isa-group/wecaremed#58]
I selected an hypothetical "CF best scenario" project to export in the monitoring phase.
In that project, during the scenario analysis, I change all the matieral from primary (100%) to recycled (100%).

But I noticed that the values in the "variables of scenario analysis" of the monitoring mode are not retained and the original situation (100% of primary) is shown.

During the export of values in the monitoring mode of the "CF best scenario", is it possible to gather also the changes in values perfomed in the variables for scenario analysis? 

Figure 1: materials in the Monitoring mode of the project
![immagine](https://user-images.githubusercontent.com/98102967/176395110-8ac456fc-5c3b-418f-8b5e-780b5b2bd372.png)

Figure 2: materials in CF desing mode  of the same project of Figure 1
![immagine](https://user-images.githubusercontent.com/98102967/176395203-98945b81-1d2a-4462-8383-f7e63a3c8ee5.png)

**Comment by jabv2022** [comment]
Please, update the tab name to "Additional data". Scenario analysis should be done manually by the user through a cloning and modifying process, where any value of both tabs (data and additional data) could be change.

**Comment by MaToSan24** [comment]
The modifications performed on a project in the "Design mode" are independent to the ones performed in the "Monitoring mode", this is the currently implemented behaviour and it is working as expected.

> During the export of values in the monitoring mode of the "CF best scenario", is it possible to gather also the changes in values perfomed in the variables for scenario analysis?

I am afraid that this is not possible.

**Comment by ARPAV2022** [comment]
This is something to be stress in a warning mask of the guidelines, because the user select the "CF best scenario" according to the modification performed in the "Data" tab but also in the "Additional data" one.

Therefore, we have to invite the user working in the "monitoring mode" to take into consideration also the "Additional data" tables and adjust them according to the real performance during the project implementation.

If I understood well, it is important the suggestion by @jabv2022 to come back to "Additional data" label instead of "Variables for sensitivity analysis", sorry.
