### ISSUE TITLE
Analysis tab

### ISSUE THREAD

**Issue by natlio** [isa-group/wecaremed#60]
I propose to reduce the decimal digits to 2 (similarly to the results of total CF)  in the CF difference between the two phases since I made a test and the result was the following

<img width="1164" alt="image" src="https://user-images.githubusercontent.com/61784811/177308854-1fe4efdf-b342-427b-a30f-4e122c0f474c.png">

Thank you.

**Comment by MaToSan24** [comment]
Done.
![image](https://user-images.githubusercontent.com/63660411/177310868-1737181a-97e3-41dc-8364-b2204a42b7ab.png)
