### ISSUE TITLE
PDF file

### ISSUE THREAD

**Issue by natlio** [isa-group/wecaremed#62]
I made a test (test3 in my account) with the following results. 
<img width="1175" alt="image" src="https://user-images.githubusercontent.com/61784811/177627012-18562fa1-e4a8-4928-8e59-375c06ea83f9.png">

When I generated the PDF file I got the following 
<img width="1175" alt="image" src="https://user-images.githubusercontent.com/61784811/177627214-cf072f01-3fdd-44c8-9942-cbe614323010.png">

Could you please clarify what is the number "19.71" in the bracket?
Also, the subscript of CO2 is not shown correctly. 

Thank you.

**Comment by MaToSan24** [comment]
> Could you please clarify what is the number "19.71" in the bracket?

This was an error, sorry for the inconvenience, it has been fixed.

Also, the subscripts now are displayed correctly.
