### ISSUE TITLE
Additional data - warning / successful messages

### ISSUE THREAD

**Issue by natlio** [isa-group/wecaremed#63]
When I modify the profiles in the tab "Additional data" in both modes , in case I have inserted by mistake values that do not sum up to 1 a warning message is shown. However , a message "Successful" is also shown at the same time. This is a bit confusing. Could you remove the "successful" message if the profile has not been set correctly?

<img width="1274" alt="image" src="https://user-images.githubusercontent.com/61784811/177766835-c0fad5f2-b4cb-4b36-84e6-36bb9547a08e.png">

**Comment by MaToSan24** [comment]
This issue has been fixed, you can find the description in the following linked issue: #64
