### ISSUE TITLE
Additional data - Events - problem with the values 

### ISSUE THREAD

**Issue by natlio** [isa-group/wecaremed#64]
I am trying to modify the percentage distribution of travels in events in the CF design mode. 

When I insert the following percentages (which sum up to1) an warning message is always shown.

<img width="1274" alt="image" src="https://user-images.githubusercontent.com/61784811/177768030-f03fe9d2-0ccf-46a6-9392-5ef0c12be008.png">

Could you please check it? 

In this case, when I return to Data and click on the Recalculate button, it does not show any warning. However, the corresponding percentages seem to set to default values again.

**Comment by MaToSan24** [comment]
We have changed this so it works in the following way: it will show only the "warning" message if the sum of the values is not equal to 1, otherwise, if the sum is equal to 1, the "successful" message is shown.

Also, the bug where values would reset to default values again has been solved as well.
