### ISSUE TITLE
Clone a Project - additional data not copied

### ISSUE THREAD

**Issue by natlio** [isa-group/wecaremed#67]
I have created a project named "test1_copy_1_Year1 " in my account. I cloned this project and renamed it as "test1_copy_1_Year1_2". All the basic input data as well as the results of CF design mode had been copied. However, the tables in the "Additional data" section had not been copied. They are set to default values. Is this a bug or it is not possible to clone these data?

**Comment by MaToSan24** [comment]
This bug has been fixed, sorry for the inconveniences.
