### ISSUE TITLE
AUTH - modifications needed in simple use mode

### ISSUE THREAD

**Issue by natlio** [isa-group/wecaremed#8]
1. **Project general data:**  In Project Starting/Finishing Year the number of years are shown as e.g. "2,021" instead of "2021". Please correct this if it is possible. Otherwise, you could add a drop down list with multiple years in order for the user to select from the list.
2. **Partners:** The columns "Personmonths PP" and "Personmonths WPP" can be merged to "Personmonths"
3. **Partners:** The column "Part-time employees" can be replaced with "Part-time/temporary employees"
4.  **Printable Deliverables:** The columns "Average number of pages" and "Paper size" is better to be also removed since default values are given. 
5. **Events, Mixed mode:both in presence and on-line**: "Average hours/day" should be replaced with "Average duration (hours/day)
6. **Events participated by the project:** The term "Average number of participants" should be replaced with "Average number of participants of the project"
7. **Events:** We suggest to add the words "number of" in all the input data related to the number of participants. e.g. "Average physical participants" to be replaced with "Average number of physical participants" etc.

**Comment by LuisUsrDev** [comment]
The year field is not showing a comma for us, please add the steps you have taken so that the field with the comma appears.

**Comment by natlio** [comment]
I click on the tab "Create new project" in the main page and then the following window appears where you have to insert the  years. I use Safari as a browser. 
<img width="596" alt="Screenshot 2022-02-10 at 12 37 17 PM" src="https://user-images.githubusercontent.com/61784811/153390312-2a06e5e3-ecf4-445d-aa1b-26625c6be65a.png">

Also, it seems it depends on the browser. Another user who used Google Chrome a point instead of comma appears.
<img width="416" alt="image" src="https://user-images.githubusercontent.com/61784811/153390653-ecb55855-ddf0-4e54-8214-78c383d1d5c0.png">
